export const countries = {
  ru: 'Русский',
  en: 'English',
  amh: 'አማርኛ ቋንቋ',
  ara: 'عربي',
  asm: 'অসমীয়া ভাষা',
  az: 'Azərbaycan',
  ben: 'বাংলা ভাষা',
  bho: 'भोजपुरी भाषा के',
  blr: 'Беларуская мова',
  ces: 'čeština',
  chan: '中国人',
  de: 'Deutsch',
  fra: 'Français',
  grk: 'Ελληνικά',
  guj: 'ગુજરાતી ભાષા',
  hau: 'Harshen Hausa',
  hin: 'हिन्दी',
  hrv: 'Hrvatski',
  hun: 'magyar nyelv',
  ibo: 'Asụsụ Igbo',
  ind: 'bahasa Indonesia',
  itl: 'Italiano',
  jav: 'basa jawa',
  jpn: '日本語',
  kan: 'ಕನ್ನಡ ಭಾಷೆ',
  kor: '한국인',
  mai: 'मैथिली भाषा',
  mal: 'മലയാളം ഭാഷ',
  mar: 'मराठा भाषा',
  mlg: 'teny malagasy',
  msa: 'Melayu',
  mya: 'ဗမာဘာသာစကား',
  nep: 'नेपाली भाषा',
  nld: 'Ede Dutch',
  ori: 'ଓଡିଆ ଭାଷା',
  orm: 'Afaan Oromoo',
  pan: 'ਪੰਜਾਬੀ ਭਾਸ਼ਾ',
  pol: 'Polski',
  por: 'Português',
  prs: 'زبان فارسی ',
  pus: 'پښتو ژبه',
  rum: 'Română',
  sin: 'සෙනගාල භාෂාව',
  sna: 'Shona mutauro',
  sndh: 'سنڌي ٻولي',
  spa: 'español',
  srik: 'Cebuano nga pinulongan',
  srp: 'Српски',
  sun: 'basa Sunda',
  tam: 'தமிழ் மொழி',
  tel: 'తెలుగు భాష',
  tha: 'ไทย',
  tur: 'Türk',
  ukr: 'Українська',
  urd: 'اردو زبان',
  uzb: "O'zbek tili",
  vie: 'ngôn ngữ tiếng Việt',
  yur: 'Èdè Yorùbá',
}
